spring.application.name=dating-ai-backend
spring.ai.openai.api-key=${SPRING_AI_OPEN_AI_API_KEY}
spring.ai.ollama.chat.enabled: false
diffusion.url=https://fe97a6a77c5448ab52.gradio.live/sdapi/v1/txt2img
profiles.path=profiles.json
startup.initializeProfiles=true
dating.ai.searchCriteria.gender=woman
dating.ai.searchCriteria.startAge=woman
dating.ai.searchCriteria.endAge=woman
# Current User's profile
dating.ai.character.user={id:'user', firstName:'ABC', lastName:'DEF', age:43, ethnicity:'Indian', gender:'MALE', bio:'Software engineer', imageUrl:'', personalityType:'INTP'}

